title: John Rey Rosales
logo: assets/me2.png
description: UI/UX Designer | Graphic Designer
show-downloads: true
theme: jekyll-theme-minimal
github:
  id: https://github.com/essrosall
  href: 'https://github.com/'
  title: 'GitHub'
  fa-icon: 'fa-github'

facebook:
  id: https://www.facebook.com/ess.rosall/
  href: 'https://twitter.com/'
  title: 'Facebook'
  fa-icon: 'fa-facebook'
