title: John Rey Rosales
logo: assets/me2.png
description: UI/UX Designer | Graphic Designer
show-downloads: true
theme: jekyll-theme-minimal

social:
  github: https://github.com/essrosall
  twitter: https://twitter.com/your-twitter-username
  facebook: https://www.facebook.com/ess.rosall/
  instagram: https://www.instagram.com/ess.rosall/
