title: John Rey Rosales
logo: assets/me2.png
description: UI/UX Designer | Graphic Designer
description: +63 993 6768 737
description: rosales.johnrey.agpalza@gmail.com
description: Novaliches, Quezon City, Metro Manila, Philippines
show_downloads: true
theme: jekyll-theme-minimal

